### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by JoePython1** [ring-clojure/ring-ssl#10]
Is there a tutorial somewhere. so I can set up a stand alone ring server with  self signed TLS cert?

**Comment by weavejester** [comment]
Ring-SSL provides middleware for use with Ring adapters that are already set up for SSL, so a tutorial like the one you describe isn't relevant to the repository.

You can use the standard Jetty adapter included in Ring to provide SSL, but a more common option (and the one I'd recommend) is to setup SSL on nginx, and proxy to your Ring adapter.
